######################################
##  Configs for the LightningModel  ##
######################################
model:
  target: models.first_stage_ss.S1ModelWithGAN
  base_learning_rate: 2.5e-5
  monitor: val/l_g_total
  monitor_mode: min
  params:
    scale: 4
    ckpt_path: 
      net_g: logs/DiffIR-official/checkpoints/SISR-DiffIRS1.pth
    net_g:
      target: modules.diff_ir.S1_arch.DiffIRS1
      params:
        n_encoder_res: 9
        inp_channels: 3
        out_channels: 3
        dim: 64
        num_blocks: [13, 1, 1, 1]
        num_refinement_blocks: 13
        heads: [1, 2, 4, 8]
        ffn_expansion_factor: 2.2
        bias: False
        LayerNorm_type: BiasFree
    net_d:
      target: modules.discriminator_arch.UNetDiscriminatorSN
      params: 
        num_in_ch: 3
        num_feat: 64
        skip_connection: True
    pix_loss_config:
      loss_weight: 1.0
      reduction: mean
    perceptual_loss_config:
      layer_weights:
        'conv1_2': 0.1
        'conv2_2': 0.1
        'conv3_4': 1
        'conv4_4': 1
        'conv5_4': 1
      vgg_type: vgg19
      use_input_norm: true
      perceptual_weight: 1.0
      style_weight: 0
      range_norm: false
      criterion: l1
    gan_loss_config:
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      loss_weight: 1.0

##################################
##  Configs for the DataModule  ##
##################################
data:
  target: data.datamodule.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    wrap: false
    train:
      target: data.downsampled_dataset.MultiScaleDownsampledDataset
      params:
        datapath: load/SalCSSR-339/HR
        min_scale: 4
        max_scale: 4
        is_train: true
        lr_img_sz: 64
        cache: memory
        data_length: 8000
        batch_size: 8
    validation:
      target: data.downsampled_dataset.DownsampledDataset
      params:
        datapath: load/benchmark/sr-geo-15/HR
        scale: 4
        is_train: false
        first_k: 2
        cache: memory

#################################
##  Configs for the Lightning  ##
#################################
lightning:
  trainer:
    max_epochs: 400
    reload_dataloaders_every_n_epochs: 1